version: "3.7"

x-base: &base
  image: django_project_template
  volumes:
    - .:/project/app
    - static:/project/static
    - media:/project/media
  depends_on:
    - postgres
    - redis
  env_file: .env

services:
  postgres:
    image: postgres:12.6-alpine

    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    image: redis:5.0.6-alpine

  django:
    <<: *base
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: runserver
    ports:
      - "8000:8000"

  bootstrap:
    <<: *base
    command: manage bootstrap

  celery:
    <<: *base
    command: celery

  celerybeat:
    <<: *base
    command: beat

volumes:
  pg-data:
  static:
  media:
