# Generated by Django 3.2.5 on 2021-07-26 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Activity description')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'busywork'), (1, 'charity'), (2, 'cooking'), (3, 'diy'), (4, 'education'), (5, 'music'), (6, 'recreational'), (7, 'relaxation'), (8, 'social')], default=0, verbose_name='Activity type')),
                ('number_of_participants', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Participants')),
                ('cost', models.PositiveSmallIntegerField(default=1, help_text='Indicative cost from 1 to 10, where 1 is free and 10 is very expensive', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Cost')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_performed', models.BooleanField(default=False, verbose_name='Already performed?')),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
                'ordering': ('-created',),
            },
        ),
    ]
